version: "3"

services: 
  # mongo: 
    # image: mongo:latest
    # container_name: mongo
    # ports:
    #   - "${MONGO_HOST_PORT}:27017"
    # volumes:
    #   - ./mongodb:/data/db

  minio: 
    image: minio/minio:latest
    container_name: minio
    networks:
      - default
    expose:
      - ${MINIO_HOST_PORT}
    ports:
      - "${MINIO_HOST_PORT}:${MINIO_HOST_PORT}"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./minio:/data
    command: server /data

  server: 
    image: minio-loompy-graphene
    container_name: server
    networks:
      - default
    expose:
      - ${GRAPHQL_PORT}
    ports:
      - "${GRAPHQL_PORT}:${GRAPHQL_PORT}"
    environment:
      - MINIO_HOST_PORT=${MINIO_HOST_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./src:/app/src
      - ./minio:/app/minio
    working_dir: /app/src
    depends_on:
      - minio
    command: uvicorn main:app --host 0.0.0.0 --port ${GRAPHQL_PORT} --reload